services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wallpaper_site
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    env_file:
      - server/.env

    ports:
      - "3000:3000"
    volumes:
      - ./server/uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        VITE_API_BASE_URL: /api
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "8080:8080"

volumes:
  mysql_data:
